version: '2'
services:
  db:
    image: mongo:3.2
    volumes:
      - "./.data/db:/data/db"
    restart: always
  chat:
    depends_on:
      - db
    image: joerter/docker-chat:latest
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      MONGO_DB: db:27017
